### ISSUE TITLE
Feature request:  Check THING for parameter and return THING.id/name if true

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#5]
Hi, I'm just starting to redo all my sensor logic with your THING and love it !! ... great work

See below use-case to explain what I want:
1) I have setup a group BATTERY_Devices
2) I want now to trigger a check (BATTERY < 10) for all devices in this group (multiple rules like in your command node)
3) Return all THING.id/names where the check (BATTERY < 10) was true
4) Return THING.id/names either as object list or as individual messages 
5) Check all items in group for THING Type and single item for THING name
6) This way I can send a warning message for all devices with battery low 

I'm already doing this with split and function nodes for other global arrays but it would be nice if that could be part of your node.. especially with the feature to handle groups

there are lot of applications to this kind of node
- with check (THING.name = *) --> output all THING.names of group --> can be used to fill a UI-Pulldown/Select box
- with check (on = true) --> create an alarm message if you forgot to switch off lights 
- with check (temp > 30 and open=true ) --> create message for all rooms with open windows/doors where temp>30

thanks for considering

**Comment by hufftheweevil** [comment]
If I'm understanding you correctly, you're basically looking for a node that will output a list of all _things_ that match some specified  condition(s). Does that sum it up?

**Comment by xX-Nexus-Xx** [comment]
yes... perfect summary

**Comment by hufftheweevil** [comment]
[v2.4.0](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v2.4.0) has the new `list` node. This will certainly be useful for many purposes. However, I want to note that I think the `trigger` node may work well for some of the situations. And now if can be configured to trigger from anything in a group, too.

For example, if you want to generate a notification when anything has a `battery < 10`, then configure a `trigger` node like so:
![image](https://user-images.githubusercontent.com/26534009/96390092-f8a54980-1180-11eb-9acb-7cc720387470.png)
That way, you don't need to poll at a regular interval, or otherwise create your own trigger.

But I can already see good uses for this list node, too. Thanks for the suggestion! I'll close this issue, but if you or anyone else has any other suggestions/issues with it, please continue the conversation.

**Comment by xX-Nexus-Xx** [comment]
Hi there,

thanks for the update, I will check right now..... and you are right that the trigger node can handle some of these case I did not realize the capability of your trigger node at the time of request ;) .. still a learning curve for me
